AWSTemplateFormatVersion: '2010-09-09'
Description: 'webCheck

  '
Globals:
  Function:
    Timeout: 3
Outputs:
  WebCheckFunction:
    Description: WebCheck Lambda Function ARN
    Value:
      Fn::GetAtt:
      - WebCheckFunction
      - Arn
  WebCheckFunctionIamRole:
    Description: Implicit IAM Role created for WebCheck function
    Value:
      Fn::GetAtt:
      - WebCheckFunctionRole
      - Arn
Resources:
  WebCheckFunction:
    Properties:
      CodeUri: s3://tschuege-deployments/04d985697a91b4c6d6e799854f6115fc
      Environment:
        Variables:
          EMAIL: juergegli@gmail.com
      Handler: app.lambda_handler
      Runtime: nodejs8.10
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
